sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=pylint
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=cov
      after_sucess: coveralls
cache: pip
install: pip install -U tox coveralls
language: python
script: tox --develop
