sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=pylint
    - python: 2.7
      env: TOXENV=py27
cache: pip
install: pip install -U tox
language: python
script: tox --develop
